config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  # get 'users' => 'users#index'
  #
  # get 'users/show'
  #
  # get 'users/new'
  #
  #
  # post 'users' => 'users#create'

#session routes
  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
#route for all destinations
  get 'users/destinations' => 'users#destinations'


  resources :users do
    resources :destinations
  end

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, presence: true, uniqueness: true
	has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]


  def index
    @user = current_user
    @destinations = @user.destinations.all
    @destination = Destination.new
  end

  def show
    @user = current_user
    @destination = Destination.find(params[:id])
    @instagram = JSON.parse(Instagram.tag_recent_media(@destination.city.tr(' ','')).to_json)
  end

  def new
    @destination = Destination.new
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def create
    @destination = current_user.destinations.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to user_destination_path(current_user, @destination), notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @destination = Destination.find(params[:id])
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to user_destination_path(current_user, @destination), notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to user_destinations_path(current_user), notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_destination
    @destination = Destination.new
  end

  def destination_params
    params.require(:destination).permit(:city, :location, :description, :user_id, :site_seen)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

	end

	def create
		@user = User.find_by(email: params[:login][:email])
		if @user &&  @user.authenticate(params[:login][:password])
			#set a cookie so our browser knows we are who we claim
			session[:user_id] = @user.id.to_s
			redirect_to user_destinations_path(current_user)
		else
			#give em another shot at logging in
			redirect_to login_path
		end
	end

	def destroy
		session.delete(:user_id)
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_destinations_path(current_user)
    else
      render :new
    end
  end

  def destinations
    @users = User.all
    @destinations = Destination.all
  end


  private
  #only allow white-listed fields to be populated and passed
  def user_params
    params.require(:user).permit(:name,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/destinations/_form.html.erb
<style>
  .field{
    margin-left: 60px;
  }
  .actions {
    margin-left: 60px;
    margin-top: 15px;
    margin-bottom: 10px;
  }
  .link-container {
    margin-left: 54px;
  }
  #text-field {
    margin-top: 5px;
    width: 300px;
    margin-bottom: -5px;
  }
</style>

<%= form_for [current_user, @destination] do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :city, placeholder: "Site Name (Be Specific)" %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, placeholder: "City, State/Country" %>
  </div>
  <div class="field">
    <%= f.label :have_you_seen_this_site? %><br>
    <%= f.check_box :site_seen%>
  </div>
  <div class="field" id="text-field">
    <%= f.text_area :description, placeholder: "Write a note here! See any other sites? What did you eat?", size: "30x6" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<style >
	body {
		min-height: 100vh;
		max-height: 100vh;
		background-image: url(http://i.imgur.com/2jcccCo.jpg);
		background-repeat: no-repeat;
		background-size: 100% 100%;
	}
</style>

<h1>Edit Site</h1>

<%= render 'form' %>

<div class="link-container">
	<%= link_to 'Back', user_destination_path(current_user,@destination) %>
	<%= link_to 'Home', user_destinations_path(current_user) %>
	<%= link_to 'Remove', user_destination_path(current_user, @destination), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/destinations/index.html.erb
<style media>
  body{
    min-height: 100vh;
    max-height: 100vh;
    background-image: url(http://i.imgur.com/g6QOXKS.jpg);
    background-repeat: no-repeat;
    background-size: 100% 100%;
  }
  th {
    font-weight: 500;
    padding-top: 10px;
  }
  td {
    padding: 5px;
  }
  .scroll-box {
    width: 680px;
    height: 350px;
    overflow-y: scroll;
  }
  ::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 5px;
  }
  ::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0, 0, 0, .3);
    -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, .5);
  }
</style>

<h1>My Sites</h1>

<div class="scroll-box">
  <table>
    <thead>
      <tr>
        <th>Site</th>
        <th>Location</th>
        <th>Seen?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @destinations.each do |f| %>
        <tr>
          <td><%= f.city %></td>
          <td><%= f.location %></td>
          <td><% if f.site_seen == true %>
                Yes
              <% else %>
                No
              <% end %>
          </td>
          <td><%= link_to 'Show', user_destination_path(current_user, f) %></td>
          <td><%= link_to 'Edit', edit_user_destination_path(current_user, f) %></td>
          <td><%= link_to 'Remove', user_destination_path(current_user, f), method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/destinations/new.html.erb
<style>
	body{
		min-height: 100vh;
		max-height: 100vh;
		background-image: url(http://i.imgur.com/slr2q2e.jpg?1);
		background-repeat: no-repeat;
		background-size: 100% 100%;
	}
	label {
		font-weight: 200;
		margin-top: 9px;
	}
</style>

<h1>Create New Site</h1>
<%= render 'form' %>

<div class="link-container">
<%= link_to 'Back', user_destinations_path %>
</div>

app/views/destinations/show.html.erb
<style media="screen">
  img {
    margin-left: -4px;
  }
  .attr-container {
    margin-left: 50px;
  }
  .link-container {
    margin-left: 56px;
    margin-bottom: 5px;
  }
  .main{
    font-weight: 400;
    font-size: 40px;
    margin-left: 35px;
    margin-bottom: -7px;
  }
  .img-container{
    text-align: center;
    margin: 0 auto;
    padding-top: 10px;
  }
  #location {
    font-size: 20px;
    font-weight: 400px;
    margin-left: -6px;
  }
  #site-seen {
    font-size: 20px;
    margin-left: -6px;
    margin-top: -3px;
  }
</style>

<div class="main">
  <%= @destination.city %>
</div>

<div class="attr-container">

  <div id="location">
    <%= @destination.location %>
  </div>

  <div id="site-seen">
  <% if @destination.site_seen == true %>
      Site<strong>Seen</strong>
  <% else %>
      Site<strong>unSeen</strong>
  <% end %>
  </div>

  <div>
    <%= @destination.description %>
  </div>

</div>

<div class="img-container">
<img src=<%= "https://maps.googleapis.com/maps/api/staticmap?center=#{@destination.location.tr(' ','+')}&zoom=12&size=320x320&maptype=roadmap&key=AIzaSyCaxPKuFEU4FfLL9Z9n13jZP_tLIs1RA4Y"%> >

<% @instagram.each do |instagram| %>
<%= image_tag instagram["images"]["low_resolution"]["url"] %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SiteSeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
    .navbar-default {
      font-size: 20px;
      background-color: rgba(255,255,255,0.7);
      border: none;
      border-radius: 0;
    }
    .navbar-brand {
      font-size: 22px;
    }


  </style>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">SiteSeer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'My Sites', user_destinations_path(current_user) %></li>
          <li><%= link_to 'All Sites', users_destinations_path%></li>
          <li><%= link_to 'New Site', new_user_destination_path(current_user) %></li>
          <li><%= link_to 'Log Out', logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to 'Sign Up!', new_user_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to current_user.email, user_destinations_path(current_user) %><li>
        <% end %>
      </ul>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/users/destinations.html.erb
<style media>
  body{
    min-height: 100vh;
    max-height: 100vh;
    background-image: url(http://i.imgur.com/XjcwBwY.jpg?1);
    background-repeat: no-repeat;
    background-size: 100% 100%;
    color: white;
  }
  th {
    font-weight: 500;
    padding-top: 10px;
  }
  td {
    padding: 5px;
  }
  .scroll-box {
    width: 700px;
    height: 350px;
    overflow-y: scroll;
  }
  ::-webkit-scrollbar {
  -webkit-appearance: none;
  width: 5px;
  }
  ::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(255, 255, 255, .3);
    -webkit-box-shadow: 0 0 1px rgba(255, 255, 255, .5);
  }
</style>


<h1>All Sites</h1>

<div class="scroll-box">
  <table>
    <thead>
      <tr>
        <th>Site</th>
        <th>Location</th>
        <th>Creator</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @destinations.each do |destination| %>
        <tr>
          <td><%= destination.city %></td>
          <td><%= destination.location %></td>
          <td><%= destination.user.name if destination.user %></td>
          <td><%= link_to 'Show', user_destination_path(current_user, destination) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<style>
	body {
		min-height: 100vh;
		max-height: 100vh;
		background-image: url(http://i.imgur.com/EE2XSpX.jpg);
		background-repeat: no-repeat;
		background-size: 100% 100%;
	}
	.main {
		font-size: 50px;
		text-align: center;
		margin-top: 130px;
	}
	.sub-header {
		font-size: 30px;
		text-align: center;
		margin-top: -5px;
	}
</style>

<div class="main">SiteSeer</div>
<div class="sub-header">See the the sites of your dreams</div>
<div class="sub-header">& re-view those you've already seen</div>

app/views/users/new.html.erb
<style>
	.form-container {
		margin-left: 50px;
	}
	input {
		margin-bottom: 5px;
	}
	body {
		min-height: 100vh;
		max-height: 100vh;
		background-image: url(http://i.imgur.com/q9izt5N.jpg);
		background-repeat: no-repeat;
		background-size: 100% 100%;
	}
	h1 {
		color: white;
	}
	p {
		margin-top: -83px;
		color: white;
	}
</style>

<h1>Create a New Account!</h1>
<div class="form-container">
<%= form_for @user do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br>
	<%= f.text_field :email, placeholder: 'E-mail' %><br>
	<%= f.password_field :password, placeholder: 'Password' %><br>
	<%= f.submit "Submit" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>